1. Импортируйте пакет numpy под именем np

In [3]:
import numpy as np

2. Распечатайте версию numpy

In [6]:
print(np.__version__)

1.26.4


3. Создайте вектор со значениями от 10 до 49 

In [42]:
arr = np.arange(10,50,1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

In [44]:
arr = np.flip(arr)
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [54]:
arr = np.random.random((5,5))
print(arr)

[[0.5647143  0.10746355 0.75092952 0.50970272 0.95496054]
 [0.80815014 0.16714413 0.26154564 0.96951643 0.10838809]
 [0.89721553 0.76116265 0.74874052 0.09987808 0.48967939]
 [0.31171768 0.51846111 0.44552331 0.35725765 0.29444406]
 [0.92014187 0.97885151 0.26388679 0.80146137 0.49590763]]


In [56]:
np.mean(arr, axis = 0)

array([0.7003879 , 0.50661659, 0.49412516, 0.54756325, 0.46867594])

In [58]:
np.median(arr, axis=0)

array([0.80815014, 0.51846111, 0.44552331, 0.50970272, 0.48967939])

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [60]:
a = np.array([x for x in range(27)])

In [74]:
a = a.reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [80]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

In [82]:
a = np.int_(a)
print(a)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [84]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

In [86]:
a = np.bool_(a)
print(a)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [129]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [133]:
sum = np.hstack((a1, a2))
print(sum)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [135]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

In [137]:
sum = np.vstack((a1, a2))
print(sum)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [141]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

In [145]:
c = np.where(a == b)
c

(array([0, 3, 4], dtype=int64),)

12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [157]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

In [161]:
c = np.dot(a, b)
print(c)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [59]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

In [163]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [165]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [169]:
angles = np.array([3.14, 3.14/2, 6.28])

In [173]:
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [177]:
v = np.random.random(size=[10])
print(v)

[0.54486231 0.27308252 0.88127628 0.17696423 0.61084533 0.30776397
 0.99364652 0.11197037 0.615268   0.21735783]


In [179]:
print(np.sort(v))

[0.11197037 0.17696423 0.21735783 0.27308252 0.30776397 0.54486231
 0.61084533 0.615268   0.88127628 0.99364652]


16. Проверить, одинаковы ли два NumPy массива

In [181]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [193]:
print(np.array_equal(a,b))

True


17. В одномерном массиве заменить максимальный элемент на ноль

In [213]:
Z = np.random.random(10)

In [215]:
Z

array([0.6031414 , 0.65010664, 0.79847357, 0.27784886, 0.96065454,
       0.71782693, 0.70727156, 0.45268634, 0.04419124, 0.49817047])

In [219]:
np.put(Z, [np.argmax(Z)], 0)
print(Z)

[0.6031414  0.65010664 0.         0.27784886 0.         0.71782693
 0.70727156 0.45268634 0.04419124 0.49817047]


18. Замените все нечетные числа одномерного массива на -1.

In [227]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
arr = np.where(arr%2 == 0, arr, -1)

In [231]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [267]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [269]:
arr = np.where(arr < 30, arr, 10)
arr = np.where(arr >= 5, arr, 10)
print(arr)

[10 10 20 10 10  5  6 10  8 10]


In [271]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [277]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

In [279]:
a = np.sort(a, 0)
a

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])