### Библиотека NumPy

Библиотека NumPy лежит в основе стека машинного обучения на Python и позволяет эффективно работать со структурами данных, часто используемыми в машинном самообучении: векторами, матрицами и тензорами. 

In [1]:
import numpy as np

#### 1.1 Создание вектора

In [3]:
# Создать вектор как строку
vector_row = np.array([1, 2, 3])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
print(vector_row)

[1 2 3]


In [5]:
# Создать вектор как столбец
vector_column = np.array([[1], [2], [3]])

In [6]:
vector_column

array([[1],
       [2],
       [3]])

## Формирование вектора
np.arange(0,10,2)

In [8]:
# Вектор из нулевых элементов
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# Единичный вектор
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# Равномернораспределенный на отрезке вектор
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [6]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

#### 1.2 Создание массива

In [12]:
# Создать матрицу
matrix = np.array([[1, 2], [1, 2 ], [1, 2]])

In [13]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [14]:
# Массив из нулевых элементов
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Единичный массив
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Единичная диагональная матрица
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 1.3. Генерирование случайных значений

In [17]:
# Задать начальное значение для генератора псевдослучайных чисел
np.random.seed(0)

In [21]:
# Сгенерировать три случайных вещественных числа между 0.0 и 1.0 
np.random.random(4)

array([0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [22]:
np.random.rand(3, 4)

array([[0.0871293 , 0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102, 0.14335329]])

In [24]:
# Сгенерировать три случайных целых числа между 1 и 10 
np.random.randint(0, 11, 3)

array([7, 3, 2])

In [25]:
# Сгенерировать нормальнораспределенный массив
np.random.randn(7)

array([ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
        1.46935877,  0.15494743])

In [25]:
np.random.randn(3, 4)

array([[ 1.62715982,  1.59456053,  0.23043417, -0.06491034],
       [-0.96898025,  0.59124281, -0.7827755 , -0.44423283],
       [-0.34518616, -0.88180055, -0.44265324, -0.5409163 ]])

In [26]:
# Извлечь три числа из нормального распределения со средним, равным 0.0,
# и стандартным отклонением, равным 1.0 
np.random.normal(0.0, 1.0, 3)

array([ 0.37816252, -0.88778575, -1.98079647])

#### 1.4. Выбор элементов

In [27]:
# Создать вектор-строку
vector = np.array([1, 2, 3, 4, 5, 6])

# Создать матрицу
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])

In [28]:
# Выбрать третий элемент вектора 
vector[2]

3

In [29]:
# Выбрать элемент на второй строке, во втором столбце 
matrix[1, 1]

5

In [30]:
# Выбрать все элементы вектора 
vector[:]

array([1, 2, 3, 4, 5, 6])

In [31]:
# Выбрать все вплоть до третьего элемента включительно 
vector[:3]

array([1, 2, 3])

In [32]:
# Выбрать все после третьего элемента 
vector[3:]

array([4, 5, 6])

In [33]:
# Выбрать последний элемент 
vector[-1]

6

In [34]:
# Выбрать первые две строки и все столбцы матрицы 
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# Выбрать все строки и второй столбец 
matrix[:,1:2]

array([[2],
       [5],
       [8]])

#### 1.5.  Описание матрицы

In [35]:
# Создать матрицу
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [37]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# Взглянуть на количество строк и столбцов 
matrix.shape

(3, 4)

In [37]:
# Взглянуть на количество элементов (строки * столбцы) 
matrix.size

12

In [38]:
# Взглянуть на количество размерностей 
matrix.ndim

2

#### 1.6.  Операции над массивами

In [2]:
# Создать матрицу
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

###### 1.6.1 Нахождение максимального и минимального элементов

In [42]:
# Вернуть максимальный элемент 
np.max(matrix)

12

In [54]:
# Вернуть минимальный элемент 
matrix.min()

1

In [55]:
# Вернуть индекс максимального элемента 
matrix.argmax()

11

In [44]:
# Найти максимальный элемент в каждом столбце 
np.max(matrix, axis=0)

array([ 9, 10, 11, 12])

In [46]:
# Найти максимальный элемент в каждой строке 
np.max(matrix, axis=1)

array([ 4,  8, 12])

###### 1.6.2 Вычисление среднего значения, дисперсии и стандартного отклонения

In [47]:
# Вернуть среднее значение 
np.mean(matrix)

6.5

In [48]:
# Вернуть дисперсию 
np.var(matrix)

11.916666666666666

In [50]:
# Вернуть стандартное отклонение 
np.std(matrix)

3.452052529534663

In [51]:
# Найти среднее значение в каждом столбце 
np.mean(matrix, axis=0)

array([5., 6., 7., 8.])

###### 1.6.3 Реформирование массивов

Метод reshape позволяет реструктурировать массив так, что мы сохраняем те же самые данные и при этом организуем их как другое количество строк и столбцов.  Единственное требование состоит в том, чтобы формы исходной и новой матриц содержали одинаковое количество элементов (т.е. матрицы имели одинаковый размер). 

In [6]:
rand_arr = np.random.randint(0,10,20)

In [7]:
rand_arr

array([8, 4, 7, 1, 6, 0, 8, 2, 0, 3, 3, 4, 2, 3, 9, 9, 4, 5, 2, 7])

In [8]:
matrix = rand_arr.reshape(4,5)

In [9]:
matrix

array([[8, 4, 7, 1, 6],
       [0, 8, 2, 0, 3],
       [3, 4, 2, 3, 9],
       [9, 4, 5, 2, 7]])

In [10]:
matrix.reshape(5, 4)

array([[8, 4, 7, 1],
       [6, 0, 8, 2],
       [0, 3, 3, 4],
       [2, 3, 9, 9],
       [4, 5, 2, 7]])

###### 1.6.4 Сглаживание матрицы

Mетод flatten представляет собой простой метод преобразования матрицы в одномерный массив.

In [11]:
# Сгладить матрицу 
matrix.flatten()

array([8, 4, 7, 1, 6, 0, 8, 2, 0, 3, 3, 4, 2, 3, 9, 9, 4, 5, 2, 7])

In [12]:
matrix.reshape(1, -1)

array([[8, 4, 7, 1, 6, 0, 8, 2, 0, 3, 3, 4, 2, 3, 9, 9, 4, 5, 2, 7]])

###### 1.6.5 Транспонирование

Транспонирование — это универсальная линейно-алгебраическая операция, в которой индексы столбцов и строк каждого элемента меняются местами

In [76]:
# Транспонировать матрицу 
matrix.T

array([[4, 7, 5, 0],
       [4, 5, 9, 1],
       [8, 5, 3, 2],
       [4, 0, 0, 4],
       [3, 1, 5, 2]])

###### 1.6.6 Определитель матрицы

In [78]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [79]:
# Вернуть определитель матрицы
np.linalg.det(matrix)

0.0

In [80]:
# Вернуть диагональные элементы 
matrix.diagonal()

array([1, 4, 9])

In [81]:
# Вырнуть след матрицы - сумма элементов главной диагонали
matrix.trace()

14

In [82]:
# Вернуть диагональ и сумму ее элементов 
sum(matrix.diagonal())

14

###### 1.6.7 Вычисление скалярных произведений

In [83]:
# Создать два вектора 
vector_a = np.array([1,2,3]) 
vector_b = np.array([4,5,6])

In [84]:
# Вычислить скалярное произведение 
np.dot(vector_a, vector_b)

32

###### 1.6.8 Арифметические операции над матрицами

In [85]:
# Создать матрицу
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

In [86]:
# Создать матрицу
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [87]:
# Сложить две матрицы
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [88]:
# Вычесть из одной матрицы другую 
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [89]:
# Сложить две матрицы 
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [90]:
# Вычесть из одной матрицы другую 
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [91]:
# Перемножить две матрицы 
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [93]:
# Перемножить две матрицы 
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [94]:
# Создать матрицу 
matrix = np.array([[1, 4],
                   [2, 5]])

In [95]:
# Вычислить обратную матрицу 
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [96]:
np.sqrt(matrix)

array([[1.        , 2.        ],
       [1.41421356, 2.23606798]])