### Задания по NumPy

1. Создайте массив из списка, состоящего из чисел от 0 до 9, при помощи функции array() из модуля numpy.

In [5]:
import numpy as np

In [13]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Создайте массив, состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля numpy.

In [15]:
odd_arr = np.arange(1,19,2)
odd_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

3. Создайте массив, состоящий из двадцати нулей.

In [17]:
zero_arr = np.zeros(20)
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

4. Создайте двумерный массив, состоящий из двадцати единиц, в котором 5 строк и 4 столбца.

In [21]:
matrix = np.ones((5,4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

5. Создайте массив, состоящий из пяти равномерно распределённых чисел от 3 до 7.

In [33]:
uniform_arr = np.linspace(3,7,5)
uniform_arr

array([3., 4., 5., 6., 7.])

6. Создайте двумерный массив, состоящий из 9 равномерно распределённых чисел от 3 до 7.

In [41]:
uniform_matrix = np.linspace(3,7,9).reshape(3,3)
uniform_matrix

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

7. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 100. Присвойте его максимальное значение переменной max_number и выведите значение этой переменной.

In [58]:
arr = np.random.randint(1,100,10)
max_num = np.max(arr)
print(arr)
print(max_num)

[26  1 28 66 12  8 92  5 68  2]
92


8. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 20. Сформируйте новый массив, состоящий из 5 элементов первого массива, начиная со 2 по порядку. Выведите значения обоих массивов.

In [56]:
rand_arr = np.random.randint(1,20,10)
second_rand_arr = rand_arr[2:7]
print(rand_arr)
print(second_rand_arr)

[12  8  8 11  6  3 18 11 16  2]
[ 8 11  6  3 18]


9. Создайте двумерный массив, состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Сформируйте новый массив, состоящий из элементов  второй и третьей строки, первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print().

In [72]:
arr = np.random.randint(3,11,12).reshape(3,4)
print(arr)
second_arr = arr[1:3,0:2]
print(second_arr)

[[ 7 10  3  8]
 [ 3  6  8  5]
 [ 3  3 10  8]]
[[3 6]
 [3 3]]


10. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print().

In [74]:
arr = np.random.randint(0,20,10)
second_arr = arr[2:]
print(arr)
print(second_arr)

[11 15 18  6  2 11  6  9 19 11]
[18  6  2 11  6  9 19 11]


11. Создайте двумерный массив, состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов.  Создайте новый массив, состоящий из элементов, больших числа 3. Выведите значения обоих массивов при помощи функции print().

In [76]:
matrix = np.random.randint(0,9,24).reshape(6,4)
arr = matrix[matrix > 3]
print(matrix)
print(arr)

[[5 3 3 4]
 [8 5 3 0]
 [8 2 2 7]
 [0 8 4 8]
 [3 2 1 8]
 [5 5 0 4]]
[5 4 8 5 8 7 8 4 8 8 5 5 4]


12. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 20. Cоздайте новый массив, состоящий из 10 элементов, начиная с 2. Выведите значения этих массивов, а также их сумму.

In [84]:
arr = np.random.randint(1,20,10)
second_arr = np.arange(2,12,1)
third_arr = arr + second_arr
print(arr)
print()
print(second_arr)
print()
print(third_arr)

[ 7  2  8  3  9 10  2  9 14 11]

[ 2  3  4  5  6  7  8  9 10 11]

[ 9  5 12  8 15 17 10 18 24 22]


13. Создайте массив, состоящий из 7 случайных целых чисел из диапазона от 0 до 9. Создайте новый массив, состоящий из 7 элементов первого массива, увеличенных в 3 раза. Выведите значения этих массивов при помощи функции print().

In [88]:
arr = np.random.randint(0,9,7)
second_arr = arr * 3
print(arr)
print()
print(second_arr)

[1 8 8 1 6 0 0]

[ 3 24 24  3 18  0  0]


14. Создайте массив, состоящий из квадратных корней 20 элементов по порядку, начиная с 7. Выведите значение массива при помощи функции print().

In [90]:
arr = np.arange(7,27,1)
print(np.sqrt(arr))

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]


15. Даны x = [1,2], y = [[4, 1], [2, 2]]. Найдите произведение матриц x * y и y * x.

In [107]:
arr = np.array([1,2])
second_arr = np.array([[4,1], [2,2]])
print(np.dot(arr, second_arr))
print(np.dot(second_arr, arr))

[8 5]
[6 6]


16. Даны x = [[1, 0], [0, 1]], y = [[4, 1], [2, 2], [1, 1]]. Найдите произведение матриц.

In [117]:
arr = np.array([[1,0], [0,1]])
second_arr = np.array([[4,1], [2,2], [1,1]])
print(np.dot(arr, second_arr))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

17. Создайте массив x, состоящий из 10 чисел от 0 до 9. Если элемент x меньше 3, замените его на 3. И если элемент x больше 7, замените его на 7. 

In [123]:
arr = np.arange(0,10,1)
print(arr)
arr[arr<3] = 3
arr[arr>7] = 7
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3 4 5 6 7 7 7]


18. Создайте массив x = np.array([1, 3, 0, -1, -3]). Вычислите поэлементно знак x (sign x).

In [125]:
arr = np.array([1,3,0,-1,-3])
print(np.sign(arr))

[ 1  1  0 -1 -1]


array([ 1,  1,  0, -1, -1])

19. Дана матрица M = [[0 5 9 8 2], [3 7 4 1 6]]. Найдите максимальное и минимальное значения и их индексы по строкам и столбцам.

In [129]:
arr = np.array([[0,5,9,8,2], [3,7,4,1,6]])
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

[3 7 9 8 6]
[9 7]


20. Создайте массив размерности 3 на 3, состоящий из чисел от 1 до 9. Вычислите среднее значение, медиану, стандартное отклонение и дисперсию.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
mean= 5.0
median= 5.0
std= 2.581988897471611
variance= 6.666666666666667
